[bodystart]
<link rel="stylesheet" href="featured-work.css" type="text/css" />
<script type="text/javascript" src="data/featured-work-slides.js"></script>
<script type="text/javascript" src="featured-work.js" defer="defer"></script>
<!-- MathJax -->
<script src='https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/latest.js?config=TeX-MML-AM_CHTML' async>
</script>
<script type="text/x-mathjax-config">
MathJax.Hub.Config({
	  TeX: { equationNumbers: { autoNumber: "AMS" } }
});
</script>
<!-- End MathJax -->
</head>
<body>
